# Generated by Django 3.2.5 on 2021-07-28 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
